apiVersion: kyverno.io/v1              # ← API group
kind: ClusterPolicy                    # ← Cluster-wide policy type
metadata:
  name: restrict-privileged           # ← Unique name for the policy

spec:
  validationFailureAction: Enforce    # ← Enforce, Audit, or warn on failure
  background: true                    # ← Apply to existing resources as well
  rules:                              # ← One or more rules can be listed
    - name: no-privileged             # ← Name of the rule
      match:
        resources:
          kinds:
            - Pod                     # ← Applies to Pod resources
      validate:                       # ← Validation logic
        message: "Privileged containers are not allowed."  # ← Message shown on denial
        pattern:                      # ← Expected structure
          spec:
            containers:
              - securityContext:
                  privileged: "false" # ← Must explicitly set privileged to false
