apiVersion: v1
kind: Pod
metadata:
  name: uc4-fail
  labels:
    app.kubernetes.io/owner: test            # ✅ UC3
spec:
  hostNetwork: true                           # ❌ Violates UC4
  containers:
    - name: nginx
      image: nginx
      securityContext:
        privileged: false                    # ✅ UC1
      resources:                             # ✅ UC2
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
