apiVersion: v1
kind: Pod
metadata:
  name: uc2-pass
  labels:
    app.kubernetes.io/env: test
spec:
  containers:
    - name: nginx
      image: nginx
      securityContext:
        privileged: false              # ✅ Satisfies UC1
      resources:                       # ✅ Satisfies UC2
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
