# Kyverno policy to enforce runAsNonRoot: true for all containers
apiVersion: kyverno.io/v1                     # Kyverno CRD version
kind: ClusterPolicy                           # Cluster-wide policy

metadata:
  name: enforce-run-as-non-root               # Unique name for this policy
  annotations:                                # Metadata annotations for clarity and tooling
    policies.kyverno.io/title: Enforce runAsNonRoot                 # Title shown in policy catalogs
    policies.kyverno.io/category: Pod Security                      # Group under security-related policies
    policies.kyverno.io/severity: high                              # High severity if this is violated
    policies.kyverno.io/description: >-                             # Policy description
      Ensures that all containers explicitly run as non-root by injecting runAsNonRoot: true.

spec:
  rules:
    - name: add-run-as-non-root               # Rule name within this policy
      match:
        resources:
          kinds:
            - Pod                             # This rule applies to all Pod resources

      mutate:                                 # Define the mutation behavior
        patchStrategicMerge:                  # Use strategic merge patch for injection
          spec:
            containers:
              - (name): "*"                   # Match all container names
                securityContext:
                  runAsNonRoot: true          # Inject this field to enforce non-root execution
