apiVersion: v1
kind: Pod
metadata:
  name: uc4-pass
  labels:
    app.kubernetes.io/owner: test
spec:
  containers:
    - name: nginx
      image: nginx
      securityContext:
        privileged: false
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
