# Kyverno policy to enforce signed image verification using Cosign
apiVersion: kyverno.io/v1                       # Kyverno CRD version
kind: ClusterPolicy                             # Cluster-wide policy

metadata:
  name: verify-signed-images                    # Unique name for this policy
  annotations:                                  # Metadata annotations for discoverability
    policies.kyverno.io/title: Require Signed Images (Cosign)               # Display title
    policies.kyverno.io/category: Supply Chain Security                     # Categorization under image security
    policies.kyverno.io/severity: high                                     # High severity due to supply chain risk
    policies.kyverno.io/description: >-                                    # Detailed description
      Verify that busybox images are signed with Cosign (yreddy007 namespace).

spec:
  validationFailureAction: Enforce              # Reject resources that fail signature checks
  background: false                             # Skip background scans (only enforce at admission time)

  rules:
    - name: require-signed-busybox              # Name of the rule
      match:
        resources:
          kinds:
            - Pod                               # Apply to Pod resources

      verifyImages:                             # Image signature verification block
        - image: "docker.io/yreddy007/busybox:*"     # Target image pattern (all tags of busybox from this namespace)
          key: |                                 # Cosign public key used to verify the image signature
            -----BEGIN PUBLIC KEY-----
            MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEgbeLsB7P3K7dGwGdxVOLuaEOvudS
            g1AXLc3qK0sMF2992uB0xlsslmG60X/Iuv6tUeIprXDOvCdH1Tpblm97bA==
            -----END PUBLIC KEY-----
          mutateDigest: true                    # Automatically resolve image to digest after signature is verified
          required: true                        # Fail the admission request if the image is not signed
