apiVersion: v1
kind: Pod
metadata:
  name: uc5-pass
  labels:
    app.kubernetes.io/owner: test
spec:
  containers:
    - name: test
      image: ghcr.io/allthingsincloud/nginx:latest  # ✅ From an approved registry
      securityContext:
        privileged: false
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
